spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: commentService
          filters:
            - MyFilterFactory
          uri: lb://commentService
          predicates:
            - Path=/comments/**
        - id: posts-service
          uri: lb://posts-service
          predicates:
            - Path=/posts/**
          filters:
            - MyFilterFactory
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
jwt:
  secret: secretkey

server:
  port: 80
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
